name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Cache multiple paths
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          ./FrameworkA/Carthage/
          ./FrameworkB/Carthage/
          ./App/Carthage/
        key: carthage-foo
        
    - name: Display content
      if: steps.cache.outputs.cache-hit == 'true'
      run: |
        du -a
        
    - name: Create content
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p FrameworkA/Carthage
        mkdir -p FrameworkB/Carthage
        mkdir -p App/Carthage
        echo "foo" > FrameworkA/Carthage/foo.txt
        echo "foo" > FrameworkB/Carthage/foo.txt
        echo "foo" > App/Carthage/foo.txt
        echo "bar" > FrameworkA/Cartfile.resolved
        echo "bar" > FrameworkB/Cartfile.resolved
        echo "bar" > App/Cartfile.resolved
